stock_data = {
    "AAPL": {
        "symbol": "AAPL",
        "company_name": "Apple Inc.",
        "current_price": 2285.17,
        "change_amount": -36.57,
        "change_percentage": -4.14,
        "market_cap": "3489B",
        "pe_ratio": 72.4,
    },
    "GOOGL": {
        "symbol": "GOOGL",
        "company_name": "Alphabet Inc.",
        "current_price": 1459.12,
        "change_amount": -6.68,
        "change_percentage": 4.53,
        "market_cap": "1652B",
        "pe_ratio": 30.9,
    },
    "AMZN": {
        "symbol": "AMZN",
        "company_name": "Amazon.com Inc.",
        "current_price": 798.45,
        "change_amount": 12.34,
        "change_percentage": 1.57,
        "market_cap": "124B",
        "pe_ratio": 15.2,
    },
    "MSFT": {
        "symbol": "MSFT",
        "company_name": "Microsoft Corporation",
        "current_price": 1325.72,
        "change_amount": 8.12,
        "change_percentage": 0.61,
        "market_cap": "2000B",
        "pe_ratio": 50.4,
    },
    "TSLA": {
        "symbol": "TSLA",
        "company_name": "Tesla Inc.",
        "current_price": 2150.65,
        "change_amount": -5.25,
        "change_percentage": -0.24,
        "market_cap": "1720B",
        "pe_ratio": 33.5,
    },
    "NVDA": {
        "symbol": "NVDA",
        "company_name": "NVIDIA Corporation",
        "current_price": 3200.84,
        "change_amount": -48.72,
        "change_percentage": -1.50,
        "market_cap": "5100B",
        "pe_ratio": 92.8,
    },
    "META": {
        "symbol": "META",
        "company_name": "Meta Platforms Inc.",
        "current_price": 490.30,
        "change_amount": 15.76,
        "change_percentage": 3.33,
        "market_cap": "650B",
        "pe_ratio": 20.1,
    },
    "NFLX": {
        "symbol": "NFLX",
        "company_name": "Netflix Inc.",
        "current_price": 1125.98,
        "change_amount": 25.34,
        "change_percentage": 2.29,
        "market_cap": "980B",
        "pe_ratio": 19.7,
    },
    "DIS": {
        "symbol": "DIS",
        "company_name": "The Walt Disney Company",
        "current_price": 1876.14,
        "change_amount": -20.19,
        "change_percentage": -1.06,
        "market_cap": "2800B",
        "pe_ratio": 45.3,
    },
    "INTC": {
        "symbol": "INTC",
        "company_name": "Intel Corporation",
        "current_price": 1350.92,
        "change_amount": 5.84,
        "change_percentage": 0.43,
        "market_cap": "1500B",
        "pe_ratio": 18.9,
    },
    "BA": {
        "symbol": "BA",
        "company_name": "Boeing Co.",
        "current_price": 215.44,
        "change_amount": -3.12,
        "change_percentage": -1.43,
        "market_cap": "245B",
        "pe_ratio": 22.1,
    },
    "V": {
        "symbol": "V",
        "company_name": "Visa Inc.",
        "current_price": 231.75,
        "change_amount": 4.19,
        "change_percentage": 1.84,
        "market_cap": "499B",
        "pe_ratio": 40.5,
    },
    "JPM": {
        "symbol": "JPM",
        "company_name": "JPMorgan Chase & Co.",
        "current_price": 152.61,
        "change_amount": -1.25,
        "change_percentage": -0.81,
        "market_cap": "469B",
        "pe_ratio": 11.7,
    },
    "WMT": {
        "symbol": "WMT",
        "company_name": "Walmart Inc.",
        "current_price": 139.08,
        "change_amount": 1.02,
        "change_percentage": 0.74,
        "market_cap": "392B",
        "pe_ratio": 25.3,
    },
    "PYPL": {
        "symbol": "PYPL",
        "company_name": "PayPal Holdings Inc.",
        "current_price": 101.12,
        "change_amount": -0.85,
        "change_percentage": -0.83,
        "market_cap": "118B",
        "pe_ratio": 33.4,
    },
    "AMD": {
        "symbol": "AMD",
        "company_name": "Advanced Micro Devices, Inc.",
        "current_price": 112.79,
        "change_amount": 4.56,
        "change_percentage": 4.21,
        "market_cap": "182B",
        "pe_ratio": 35.1,
    },
    "CRM": {
        "symbol": "CRM",
        "company_name": "Salesforce, Inc.",
        "current_price": 201.32,
        "change_amount": -2.14,
        "change_percentage": -1.05,
        "market_cap": "199B",
        "pe_ratio": 47.8,
    },
    "CSCO": {
        "symbol": "CSCO",
        "company_name": "Cisco Systems Inc.",
        "current_price": 49.73,
        "change_amount": 0.76,
        "change_percentage": 1.55,
        "market_cap": "208B",
        "pe_ratio": 17.2,
    },
    "MCD": {
        "symbol": "MCD",
        "company_name": "McDonald's Corporation",
        "current_price": 280.78,
        "change_amount": 3.35,
        "change_percentage": 1.21,
        "market_cap": "208B",
        "pe_ratio": 26.5,
    },
    "KO": {
        "symbol": "KO",
        "company_name": "The Coca-Cola Company",
        "current_price": 60.15,
        "change_amount": -0.54,
        "change_percentage": -0.89,
        "market_cap": "261B",
        "pe_ratio": 29.1,
    }
}
